### PR TITLE
Move temp Caddyfiles to a protected directory and document

### PR DESCRIPTION
**Pull request by polypixeldev**
Fix a small security issue with the temp Caddyfiles potentially being accessible to non-privileged users. Also adds some docs in SETUP.md about Nest CLI.

### CODE REVIEW

**Review by dispherical — APPROVED** [review]
It's fine, but why not use a random string for the temp files or something

**Comment by polypixeldev** [comment]
i'm not sure what you mean - like generate a new file name on every run?

**Comment by hello-smile6** [comment]
Would systemd-run + [`RuntimeDirectory`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) work for this?

**Comment by dispherical** [comment]
> i'm not sure what you mean - like generate a new file name on every run?

Yeah, but you could consider it unnecessary

**Comment by polypixeldev** [comment]
yeah, I don't think it's needed

**Comment by polypixeldev** [comment]
systemd-run could work but I feel like that's just overcomplicating it

**Pull request merged**
