### PR TITLE
feat: add basic shell update functionality

### LINKED ISSUE #49: feat: Allow user's to select their shell in nest bot
as per the conversation with @hello-smile6 on slack
```[tasklist]
### Tasks
- [ ] https://github.com/hackclub/nest/pull/50
```

### PR DESCRIPTION
**Pull request by taciturnaxolotl**
Closes #49

### CODE REVIEW

**Comment by taciturnaxolotl** [comment]
This adds a drop down to @\nestbot which fetches the available shells from `/etc/shells` and allows the user to change their shell to one of them using the authentik [core_users_update](https://docs.goauthentik.io/developer-docs/api/reference/core-users-update) api and the loginShell atribute

**Review by polypixeldev — CHANGES_REQUESTED** [review]
Looks good! Could you make it so that the select menu is de-duplicated and maybe look a little better? Like take the array of shells from /etc/shells, map it to take only the last part of the file path, and then throw it in a Set to get rid of duplicates. That way we don't end up with /bin/bash and /usr/bin/bash both being options, etc.

**Comment by taciturnaxolotl** [comment]
sure!

**Comment by taciturnaxolotl** [comment]
that should work!

**Comment by polypixeldev** [comment]
Hmm, not sure the de-duplication part is working - I ran the new code in a node repl with the /etc/shells file on my system and got this:
```
[ '/bin/sh', 'bin/sh', 'bin/bash', 'bin/tmux', '/bin/tmux' ]
```

**Comment by taciturnaxolotl** [comment]
oops; leme fix that

**Comment by taciturnaxolotl** [comment]
that should work now!

**Review by polypixeldev — APPROVED** [review]
Got `[ '/bin/sh', '/bin/bash', '/bin/tmux' ]`! LGTM then - we'll just have to do the DB migration and fill in the `pk` value for all current users, right?

**Comment by taciturnaxolotl** [comment]
yup!

**Comment by hello-smile6** [comment]
> Looks good! Could you make it so that the select menu is de-duplicated and maybe look a little better? Like take the array of shells from /etc/shells, map it to take only the last part of the file path, and then throw it in a Set to get rid of duplicates. That way we don't end up with /bin/bash and /usr/bin/bash both being options, etc.

If deduplication results in a value that doesn't exist in /etc/shells, the user will be unable to e.g. use SFTP (just pointing that out)

**Comment by hello-smile6** [comment]
> > Looks good! Could you make it so that the select menu is de-duplicated and maybe look a little better? Like take the array of shells from /etc/shells, map it to take only the last part of the file path, and then throw it in a Set to get rid of duplicates. That way we don't end up with /bin/bash and /usr/bin/bash both being options, etc.
> 
> If deduplication results in a value that doesn't exist in /etc/shells, the user will be unable to e.g. use SFTP (just pointing that out)

Also, it might be nice to specifically show both /usr/local/bin (or elsewhere) and /usr/bin so that users can use a shell compiled from source on nest if needed (if that ever happens, that is)

**Comment by taciturnaxolotl** [comment]
I can do that!

**Comment by taciturnaxolotl** [comment]
@hello-smile6 by showing `/usr/bin` do you mean the shells inside `/usr/bin`?

**Comment by taciturnaxolotl** [comment]
> If deduplication results in a value that doesn't exist in /etc/shells, the user will be unable to e.g. use SFTP (just pointing that out)

I was able to fix that by just pulling directly from the file with a map

**Review by polypixeldev — APPROVED** [review]

**Review by hello-smile6 — APPROVED** [review]

**Review by cskartikey — APPROVED** [review]

**Comment by taciturnaxolotl** [comment]
Can this be merged now?

**Comment by polypixeldev** [comment]
Merged and db has been migrated - need to write a script though to update the DB with `pk` values from Authentik

**Pull request merged**
