### PR TITLE
Add hackverify mandate to nest bot

### PR DESCRIPTION
**Pull request by dispherical**

### CODE REVIEW

**Review by polypixeldev — CHANGES_REQUESTED** [review]
I think it might make it easier for the user if it checked when you clicked the button to signup, before you went in and entered all of your info. Like instead of opening the form, open a small view that has that text.

Other than that though LGTM

**Comment by dispherical** [comment]
Will fix tomorrow

**Comment by dispherical** [comment]
Faisal showed me the official API so I migrated to that.

**Review by hello-smile6 — APPROVED** [review]
LGTM

**Pull request merged**
