### PR TITLE
Caddyfile validation

### PR DESCRIPTION
**Pull request by polypixeldev**
Makes sure that we don't break Caddy! Breaking Caddy is bad

### CODE REVIEW

**Review by reesericci — CHANGES_REQUESTED** [review]
could we also run caddy fmt?

**Review by reesericci — CHANGES_REQUESTED** [review]
I think we should format the change not risk formatting the entire thing

**Comment by polypixeldev** [comment]
What's wrong (or could go wrong) with formatting the whole thing in contrast to just the change?

**Comment by reesericci** [comment]
Idk if something is messed up in another section it could overwrite it

**Comment by polypixeldev** [comment]
If there's a syntax error then the validate before the format will catch it, everything should be formatted anyways

**Comment by reesericci** [comment]
Alr

**Review by reesericci — APPROVED** [review]

**Pull request merged**
